### ISSUE TITLE
Integrate components

### ISSUE THREAD

**Issue by epvienneau** [epvienneau/skin_lesion_classification_app#11]

**Comment by polortiz4** [comment]
Note: use React Routing

**Comment by polortiz4** [comment]
Actually... I'm starting to think we need react native navigator instead of router (I think the router one works better for react and navigator for react native)

**Comment by juliaross20** [comment]
Let us know when you add that to the App.js so we can put our components in there!

**Comment by polortiz4** [comment]
It's up! I made a pull request to merge it to master.. the way in which the navigation shouldn't be hard to understand from the code, so you can just replicate it.. Let me know if you like it/it works

**Comment by epvienneau** [comment]
This works!
