### ISSUE TITLE
Call get_prediction in Upload.js

### ISSUE THREAD

**Issue by epvienneau** [epvienneau/skin_lesion_classification_app#28]
Need to figure out how to 1) import, 2) call, and 3) receive output from get_prediction in Upload.js to achieve the core functionality of our project

**Comment by epvienneau** [comment]
get_prediction works!

**Comment by mlp6** [comment]
[nit] don't forget to associate commit IDs with the issues.  🌊

**Comment by epvienneau** [comment]
I know I know you’re right we forgot in all the excitement sorry! 🙈
