### ISSUE TITLE
Store the input image into a folder in the local computer

### ISSUE THREAD

**Issue by polortiz4** [epvienneau/skin_lesion_classification_app#48]
Since the impath stored in the database refers to a local address, we need to somehow save the uploaded image.. Shouldn't be too bad.. Some how in the prediction function we could do the python equivalent to imwrite or something.. then wherever we write that file to, we need to pass the address to the function uploadimage to store it in the database... Or something along those lines

**Comment by juliaross20** [comment]
pablo crushed it and now it's stored as base 64 string :)
