### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by polortiz4** [epvienneau/skin_lesion_classification_app#57]
Not sure if these should be done

**Comment by epvienneau** [comment]
Yes this should be done

**Comment by epvienneau** [comment]
<img width="1276" alt="screen shot 2017-12-13 at 10 05 29 pm" src="https://user-images.githubusercontent.com/31496393/33973625-e6ef3f2e-e051-11e7-9d71-5a1982c70ae9.png">
Cannot figure this one out...

**Comment by suyashkumar** [comment]
Ah...so this is because tensorflow is installed only inside the Docker container but the docs are being built outside the Docker container. One way to fix this is to install tensorflow globally on the machine where you are building docs `pip install tensorflow`. 

Another solution would be to have the `make html` run inside the Docker container by exec'ing in...but no worries on that front, installing tensorflow on the machine to build docs should be fine.

**Comment by suyashkumar** [comment]
you could also try to run the docs process inside the docker container by doing the following, but it's definitely a little more work...

`docker ps` to find the server container id
then `docker exec -it <server container id> bash`
(now you're inside the container where tensorflow is available)
assuming you've installed sphinx already (`pip install Sphinx`) you should be able to just run all the needed commands...

**Comment by epvienneau** [comment]
Thanks Suyash! Pablo somehow got this working. even pulling down his Pablo/Sphinx branch and following his same steps, it still doesn't work for me, so I'm going to let him handle this one.

**Comment by polortiz4** [comment]
@mlp6 @suyashkumar .. From the Sphinx guidelines, we're supposed to gitignore any _build/ directory, but... If so, how can you see the documentation?

**Comment by mlp6** [comment]
End user would build it in the format they want with the `Makefile`!

**Comment by polortiz4** [comment]
But that means they would need to have all the dependencies installed, right?

**Comment by polortiz4** [comment]
And with Emelina we noticed that’s a little more complicated than activating the environment

**Comment by polortiz4** [comment]
@epvienneau

**Comment by epvienneau** [comment]
Yea I was unable to generate the docs for myself actually :(
