### ISSUE TITLE
Exceptions 

### ISSUE THREAD

**Issue by polortiz4** [epvienneau/skin_lesion_classification_app#58]
Try testing multiple ways people could break our webpage and add exceptions for that. Quick examples thay come to mind:
-Trying to create a  user whose username already exist. (I wrote something for this in main.py, but it isn't great... worth checking)
-Inputting some file of unexpected format
-Trying to create a user without filling out all the fields.

Thought of a new one that's giving errors:
- Clicking The Get Prediction button before the Choose and Image Button
- Pressing the Home button before get predictions has finished running (this one I guess is more optional)

**Comment by epvienneau** [comment]
almost broke the app, but its done...
