### ISSUE TITLE
Travis won't recognize yml file

### ISSUE THREAD

**Issue by epvienneau** [epvienneau/skin_lesion_classification_app#84]
Really at a loss here...

**Comment by mlp6** [comment]
Do you have an error message from the build site?

**Comment by epvienneau** [comment]
<img width="917" alt="screen shot 2017-12-14 at 4 17 58 pm" src="https://user-images.githubusercontent.com/31496393/34014792-69aa452e-e0ea-11e7-89c4-948ec496e73c.png">

**Comment by epvienneau** [comment]
Most of the time it's just been saying "sorry, request rejected" 
This time there's an actual error.

**Comment by epvienneau** [comment]
it also says at the top remove awkward node_modules... @polortiz4 you mentioned this, what does this mean?

**Comment by epvienneau** [comment]
Ah just merged your pr pablo thanks

**Comment by epvienneau** [comment]
(for the record, py.test passed locally this morning at approx 11:47)

**Comment by epvienneau** [comment]
suyash fixed!
